# -*- coding: utf-8 -*-
"""if else 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_4mDdepVSqGFFprt2j3ZXSipHE0rPIc8

## CONDITIONAL STATMENT (IF ELSE)

```python
if condition:
    print("execute this statement")
else:
    print("if condition is not True")

if its is raining then let's work from home else let's go to office
"""

raining = True

if raining: # TRUE CONDITION 
    print("Lets do work from home") # This statemen exectuted
else:
    print("Lets go to office")

"""if its is raining then let's work from home else let's go to office"""

raining = False # its not raining

if raining: # FALSE CONDITION
    print("Lets do work from home") # 
else:
    print("Lets go to office") # This statemen exectuted

"""### use of indentation"""

raining = True

if raining: # TRUE CONDITION 
print("Lets do work from home") # This statemen exectuted
else:
  print("Lets go to office")

raining = True

if raining: # TRUE CONDITION 
    print("Since its raining...")
    print("Lets do work from home") # This statemen exectuted
else:
    print("Since its not raining...")
    print("Lets go to office")

"""if it's NOT raining then let's let's go to office ELSE let's work from home"""

raining = True

if not raining: # False CONDITION 
    print("Since its not raining...")
    print("Lets go to office")    
else:
    print("Since its raining...")
    print("Lets do work from home") # This statemen exectuted

raining = False

if not raining: # False CONDITION 
    print("Since its not raining...")
    print("Lets go to office")    
else:
    print("Since its raining...")
    print("Lets do work from home") # This statemen exectuted

class_started = False

if class_started:
    print("Lets concentrate")
else:
    print("Lets revise previous class")

"""##  Logical opertors 

Keywords | Meaning
- | - 
not | unary negation
and | conditional AND
or | conditional OR

if class started then let's concentrate else revise the previous class
"""

class_started = True

if class_started:
    print("Since class started...")
    print("Lets concentrate")
else:
    print("Since class is not started...")
    print("let's revise")

class_started = False

if class_started:
    print("Since class started...")
    print("Lets concentrate")
else:
    print("Since class is not started...")
    print("let's revise")

"""if class NOT started then let's revise else let's concentrate class"""

class_started = True

if not class_started:
    print("Since class is not started...")
    print("let's revise")
else:
    print("Since class started...")
    print("Lets concentrate")

class_started = False

if not class_started:
    print("Since class is not started...")
    print("let's revise")
else:
    print("Since class started...")
    print("Lets concentrate")

# statements not alligned properly will give indentation error
class_started = False

if not class_started:
 print("Since class is not started...")
  print("let's revise")
else:
print("Since class started...")
    print("Lets concentrate")

# statements not alligned properly will give indentation error
class_started = False

if not class_started:
    print("Since class is not started...")
    print("let's revise")
else:
    print("Since class started...")
    print("Lets concentrate")

# # statements not alligned properly will give indentation error
# ## lets take it at the end:
# class_started = bool(input("Hey friend, is class started?: [0-False/1-True]"))

# if class_started:
#     print("Since class started...")
#     print("Lets concentrate")
# else:
#     print("Since class is not started...")
#     print("let's revise")

"""Vegetable | Salt | Dish
- | - | -
False | False | False
False | True | False
True | False | False
True | True | True
"""

vegetable_present = False
salt_present = False

if vegetable_present and salt_present:
    print("Its a good dish")
else:
    print("Its a bad dish")
    print(f"because vegetable present: {vegetable_present}")
    print(f"and salt present: {salt_present}")

vegetable_present = False
salt_present = True

if vegetable_present and salt_present:
    print("Its a good dish")
else:
    print("Its a bad dish")
    print(f"because vegetable present: {vegetable_present}")
    print(f"and salt present: {salt_present}")

vegetable_present = True
salt_present = False

if vegetable_present and salt_present:
    print("Its a good dish")
else:
    print("Its a bad dish")
    print(f"because vegetable present: {vegetable_present}")
    print(f"and salt present: {salt_present}")

"""if vegetable and salt both are present in my dish then only my dish is good."""

vegetable_present = True
salt_present = True

if vegetable_present and salt_present: # this condition was true as both the sub conditions are true
    print("Its a good dish")
else:
    print("Its a bad dish")
    print(f"because vegetable present: {vegetable_present}")
    print(f"and salt present: {salt_present}")

name = "Satyam"
print(f"hi class my name is: {name}")

"""### or conditional OR

if I have a car or bike then I can travel 100kms in a day

Car | Bike | Travel_100_kms
- | - | -
False | False | False
False | True | True
True | False | True
True | True | True
"""

i_own_car = False
i_own_bike = False

if i_own_car or i_own_bike:
    print("I can travel 100 kms in a day!")
else:
    print("I am stuck as I don't have car or bike!")

i_own_car = False
i_own_bike = True

if i_own_car or i_own_bike:
    print("I can travel 100 kms in a day!")
else:
    print("I am stuck as I don't have car or bike!")

i_own_car = True
i_own_bike = False

if i_own_car or i_own_bike:
    print("I can travel 100 kms in a day!")
else:
    print("I am stuck as I don't have car or bike!")

i_own_car = True
i_own_bike = True

if i_own_car or i_own_bike:
    print("I can travel 100 kms in a day!")
else:
    print("I am stuck as I don't have car or bike!")

"""## Conclusion - 
1. use and operator when you want all the condition to be true
2. use or operator if anyone of the condition you want to be true

### example-

attendance | assignment | eligible_for_exam
- | - | -
>=75% | >=70% | True
"""

attendance = 70
assignment_submitted = 40

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")

if attendance >= 75 and assignment_submitted >= 70:
    print("The student is eligible to appear in final exam")
else:
    print("The student is not eligible")

attendance = 90
assignment_submitted = 40

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")

if attendance >= 75 and assignment_submitted >= 70:
    print("The student is eligible to appear in final exam")
else:
    print("The student is not eligible")

attendance = 90
assignment_submitted = 90

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")

if attendance >= 75 and assignment_submitted >= 70:
    print("The student is eligible to appear in final exam")
else:
    print("The student is not eligible")

"""
credit_card | debit_card | purchase_book_from_amazon
- | - | -
True | True | True
False | False | True"""

own_credit_card = False
own_debit_card = False

if own_credit_card or own_debit_card:
    print("proceed further for payment")
else:
    print("Ask from a dad for debit or credit card?")
    print("cash on delivery?")

own_credit_card = False
own_debit_card = True

if own_credit_card or own_debit_card:
    print("proceed further for payment")
else:
    print("Ask from a dad for debit or credit card?")
    print("cash on delivery?")

own_credit_card = False
own_debit_card = False
Net_banking = True

if own_credit_card or own_debit_card or Net_banking:
    print("proceed further for payment")
else:
    print("Ask from a dad for debit or credit card?")
    print("cash on delivery?")

## and or together

attendance | assignment | sports_player | eligible_for_exam
- | - | - | -
>=75% | >=70% | False | True
>=75% | >=70% | True | True

attendance = 70
assignment_submitted = 40
sports_player = True

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")
print(f"sports criteria met? : {sports_player}")

if attendance >= 75 and assignment_submitted >= 70:
    if sports_player:
        print("The student is eligible to appear in final exam")
    else:
        print("The student is eligible to appear in final exam")
else:
    print("The student is not eligible")

"""if attendence is more than 75% and assignment completed more than 70% OR the student is sports player then only the student is eligible for exam

if you are sports player then you will get grace marks = +10
"""

# complex conditional casses as mentioned above -
attendance = 90 # mendatory
assignment_submitted = 75 # mendatory
sports_player = False # not mendatory

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")
print(f"sports criteria met? : {sports_player}")

if attendance >= 75 and assignment_submitted >= 70:
    if sports_player:
        print("The student is can get grace marks = +10")
    else:
        print("The student is eligible to appear in final exam but not extra grace marks")
else:
    print("The student is not eligible")

# complex conditional casses as mentioned above -
attendance = 90 # mendatory
assignment_submitted = 75 # mendatory
sports_player = True # not mendatory

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")
print(f"sports criteria met? : {sports_player}")

if attendance >= 75 and assignment_submitted >= 70:
    if sports_player:
        print("The student can get grace marks = +10")
    else:
        print("The student is eligible to appear in final exam but not extra grace marks")
else:
    print("The student is not eligible")

# complex conditional casses as mentioned above -
attendance = 90 # mendatory
assignment_submitted = 40 # mendatory
sports_player = True # not mendatory

print(f"attendence criteria met? : {attendance >= 75}")
print(f"assignment criteria met? : {assignment_submitted >= 70}")
print(f"sports criteria met? : {sports_player}")

if attendance >= 75 and assignment_submitted >= 70:
    if sports_player:
        print("The student can get grace marks = +10")
    else:
        print("The student is eligible to appear in final exam but not extra grace marks")
else:
    print("The student is not eligible")

"""Operator | uses | Meaning
- | - | -
is | A is B=> | return True if A and B points to the same object   
is not | A is not B | returns True if A and B do not points to the same object
== | A == B | A is equal to B
!= | A != B | A is not equal to B

When using `is` then we are also comparing memory location
When using `is not` then we are also comparing memory location

== and != is only checking value of the variables [Used more offently or frequently]
"""

A = 1
B = 1

if A is B:
    print("A and B are same")
else:
    print("A and B are not same")

id(A)

id(B)

A = 1
B = 2

if A is B:
    print("A and B are same")
else:
    print("A and B are not same")

A = 1
B = 2

if A is not B:
    print("A and B are not same")
else:
    print("A and B are same")

A = 1
B = 1

if A == B: # A and B are having same value
    print("A and B are same")
else:
    print("A and B are not same")

A = 1
B = 2

if A != B:
    print("A and B are not same")
else:
    print("A and B are same")

A = "Sunny"
B = "Sunny"

A is B

A = ["Sunny", "Rishav"]  # list data structure # array in other language
B = ["Sunny", "Rishav"]  # list data structure

A is B

A == B

A is not B

id(A)

A = int(input("Enter the value of A: "))
B = int(input("Enter the value of B: "))

A is B