# -*- coding: utf-8 -*-
"""Variable.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qU62bo9vS0v_nEOBVCvc4fYlXqcAvGs1

# Print statement
"""

print("Hello Neurons")

print("greetings from iNeuron")
print("Good Evening")

print('greetings from iNeuron')
print("Good Evening")

Print("Good Evening")

print "Good Evening"

print("Good 
Evening")

"Good morning"

"Good morning"
print("HI")

print("""Good 
Evening""")

print("""India, officially the Republic of India (Hindi: Bhārat Gaṇarājya),[26] is a country in South Asia. It is the seventh-largest country by area, the second-most populous country, and the most populous democracy in the world. Bounded by the Indian Ocean on the south, the Arabian Sea on the southwest, and the Bay of Bengal on the southeast, it shares land borders with Pakistan to the west;[f] China, Nepal, and Bhutan to the north; and Bangladesh and Myanmar to the east. In the Indian Ocean, India is in the vicinity of Sri Lanka and the Maldives; its Andaman and Nicobar Islands share a maritime border with Thailand, Myanmar, and Indonesia. The nation's capital city is New Delhi.

Modern humans arrived on the Indian subcontinent from Africa no later than 55,000 years ago.[27][28][29] Their long occupation, initially in varying forms of isolation as hunter-gatherers, has made the region highly diverse, second only to Africa in human genetic diversity.[30] Settled life emerged on the subcontinent in the western margins of the Indus river basin 9,000 years ago, evolving gradually into the Indus Valley Civilisation of the third millennium BCE.[31] By 1200 BCE, an archaic form of Sanskrit, an Indo-European language, had diffused into India from the northwest.[32][33] Its evidence today is found in the hymns of the Rigveda. Preserved by a resolutely vigilant oral tradition, the Rigveda records the dawning of Hinduism in India.[34] The Dravidian languages of India were supplanted in the northern and western regions.[35] By 400 BCE, """)

print("""Good 
Evening
from
India""")

"""Comment

"""

# say hello to the students
print("Hi Students")

# say hello to the students
# print("Hi Students")

"""# Multi line comments

Say Hi
To the students
"""

"""
Say Hi
To the students
"""
print('Hi Students')

# Say Hi
# To the students

print('Hi Students')

# more exceptional cases in print statements

print("Hi my name is "vani" ")

print("Hi my name is \"vani\" ")

print('Hi my name is "vani" ')

print("Hi my name is 'vani' ")

print("""Hi my name is "vani" """)

print("""Hi my name is "vani"!""")

"""Example [Shift + Enter]"""

123 + 245 # Sum of 2 nos

123 * 245

123 / 245

123**2 # power of 123 raised to 2

(-123)**2

123%2 # modulo operator which gives you reminder

2%2

3%2

122%2

123 * 245
print("Result")

print(123 * 245)
print("Result")

print("123 * 245")
print("Result")

"""# Variables in python"""

x = 10

print(x)

y = 20

print(y)

print(x + y)

print(x / y)

"""1. Variable names should start with alphabets"""

ten = 10
ten_number = 10
tenNumber = 10

"""2. Variable names should not contain any special characters like ^ % $ ! @ # ^ & * ( )


"""

ten* = 10

ten%number = 10

ten = 10
ten_number = 10
ten%number = 10
tenNumber = 10

ten = 10
ten_number = 10
ten/number = 10
tenNumber = 10

"""3. Variable names can contain numbers but you can't start with numbers"""

ten10 = 10

10ten = 10

__num = 10 # hidden variable

"""4. Its not a strict rule that you should variable names with a Captial letter. But its recommended to use small letters for the variables"""

Ten = 10

ten number = 10

ten_number = 10

_ = 10 # dummy variable

"""# Fundamental data types

# integers
"""

a = 7

type(a)

b = 77777
type(b)

"""floats - numbers containing decimal numbers


"""

pi = 3.14

type(pi)

pi = 22/7
pi

type(pi)

x = 2.0

type(x)

"""# Complex numbers"""

a = 2+3j
a

type(a)

a.real

a.imag

"""## Dynamic typing"""

a = 22
type(a)
a = 22.2
type(a)

a = 22
print(type(a))
a = 22.2
print(type(a))
a = "vani" 
print(type(a))
a = 'vani' 
print(type(a))

a = 22
print(type(a))
a = 22.2
print(type(a))
a = "22.2" 
print(type(a))

"""# Strong typing"""

"Day " + 1

22.2 + 1

"Day " + "1"

22 + 22

"22" + "22"

"22" + 22

22 + "22"

'22' + "22"

"chandra " + "vani"

a = 1 # int data type
b = 1.2 # float data type
c = "chandravani" # string data type 
f = 1 + 2j # complex data type # rarely used

print("Hi welcome to class of python language")

print("Hi welcome to class of Java language")

language = "JavaScript"
print("Hi welcome to class of " + language + " language") # allowed but rarely used

# f -> formatted string method
language = "JavaScript"
print(f"Hi welcome to class of {language} language") # current standard approach used in python

language = "JavaScript"
print("Hi welcome to class of {} language".format(language)) # old way

language = "JavaScript"
print("Hi welcome to class of {language} language")

# f -> formatted string method
num = "first"
language = "Python"
print(f"Today is the {num} class of {language} language") # current standard approach used in python

num = "first"
language = "Python"
print("Today is the {} class of {} language".format(num, language))

num = "first"
language = "Python"
print("Today is the "+num+" class of "+language+" language")

a = 22
b = 34
c = a + b
print(f"the result sum of two nums a: {a} and b: {b} is ={c}")

"""# Boolean
True False
"""

one = True
two = False

print(type(one))
print(type(two))

class_starts_at = 3 
you_came_at = 2
you_understood_all_concepts = you_came_at < class_starts_at

print(f"You understood everything?: {you_understood_all_concepts}")

class_starts_at = 3 # class start at 3 PM
you_came_at = 4 # you came to class at 4 PM
you_understood_all_concepts = you_came_at < class_starts_at

print(f"You understood everything?: {you_understood_all_concepts}")

# = means assignment
# == means comparing equality
is_raining = False
umbralla_available = False
go_to_college = is_raining == umbralla_available # Cop
go_to_college

numA = 5
numB = 6
numA == numB

numA = 5
numB = 5
numA == numB

numA = 5
numB = 5
numA > numB

numA = 5
numB = 5
numA >= numB

